config/routes.rb
Rails.application.routes.draw do
  resources :pedido_produtos
  resources :pedidos
  resources :produtos
  resources :enderecos
  resources :clientes

  root to: 'clientes#new'
  
  get '/obrigado', to: 'clientes#obrigado'

  #  rota , to: controler#ação
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
	validates :cpf, uniqueness: true
end
# comando que valida: campo, único: verdadeiro

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to "/obrigado"} #redireciona para página "obrigado"
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente foi eliminado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def obrigado
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :cpf, :email, :telefone)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_msg">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

    </div>
  <% end %>

 
  

<div class="cartao">
<div>
  
      <%= form.label :nome %>
      <%= form.text_field :nome %>


      <%= form.label :cpf %> 
      <%= form.text_field :cpf %>



      <%= form.label :email %>
      <%= form.text_field :email %>



      <%= form.label :telefone %>
      <%= form.text_field :telefone %> 
</div>


<%= form.submit "Salvar agora", class: "botao" %>



</div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Alteração Cliente</h1>


<%= render 'form', cliente: @cliente %>


<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
  <div class="titulos_tabela>"
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </div>  
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Novo Registro', new_cliente_path, class: "botao" %>

app/views/clientes/new.html.erb
<img title="Igreja Monte Sião" src="/logoIMS.png" align="Center"/>

<h1>Olá!</h1>
<h3>Bem-Vindo!</h3>


<%= render 'form', cliente: @cliente %>

<!--    <%= link_to 'Voltar', clientes_path %>    -->

app/views/clientes/obrigado.html.erb
<h1>Obrigado!</h1>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @cliente.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<footer>
  <%= link_to 'Editar', edit_cliente_path(@cliente) %> |
  <%= link_to 'Voltar', clientes_path %>
</footer>


<strong>...................</strong>
<div id="st"> </div>
<div class="classe">   I    M    S </div>