config/routes.rb
Rails.application.routes.draw do
  resources :pedido_produtos
  resources :pedidos
  resources :produtos
  resources :enderecos
  resources :clientes

  root to: 'clientes#new'
  
  get '/obrigado', to: 'clientes#obrigado'

  #  rota , to: controler#ação
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pedido_produto.rb
class PedidoProduto < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
end

app/controllers/pedido_produtos_controller.rb
class PedidoProdutosController < ApplicationController
  before_action :set_pedido_produto, only: [:show, :edit, :update, :destroy]

  # GET /pedido_produtos
  # GET /pedido_produtos.json
  def index
    @pedido_produtos = PedidoProduto.all
  end

  # GET /pedido_produtos/1
  # GET /pedido_produtos/1.json
  def show
  end

  # GET /pedido_produtos/new
  def new
    @pedido_produto = PedidoProduto.new
  end

  # GET /pedido_produtos/1/edit
  def edit
  end

  # POST /pedido_produtos
  # POST /pedido_produtos.json
  def create
    @pedido_produto = PedidoProduto.new(pedido_produto_params)

    respond_to do |format|
      if @pedido_produto.save
        format.html { redirect_to @pedido_produto, notice: 'Pedido produto was successfully created.' }
        format.json { render :show, status: :created, location: @pedido_produto }
      else
        format.html { render :new }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedido_produtos/1
  # PATCH/PUT /pedido_produtos/1.json
  def update
    respond_to do |format|
      if @pedido_produto.update(pedido_produto_params)
        format.html { redirect_to @pedido_produto, notice: 'Pedido produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido_produto }
      else
        format.html { render :edit }
        format.json { render json: @pedido_produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedido_produtos/1
  # DELETE /pedido_produtos/1.json
  def destroy
    @pedido_produto.destroy
    respond_to do |format|
      format.html { redirect_to pedido_produtos_url, notice: 'Pedido produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido_produto
      @pedido_produto = PedidoProduto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_produto_params
      params.require(:pedido_produto).permit(:pedido_id, :produto_id, :valor)
    end
end

app/helpers/pedido_produtos_helper.rb
module PedidoProdutosHelper
end

app/views/pedido_produtos/_form.html.erb
<%= form_with(model: pedido_produto, local: true) do |form| %>
  <% if pedido_produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido_produto.errors.count, "error") %> prohibited this pedido_produto from being saved:</h2>

      <ul>
      <% pedido_produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pedido_id %>
    <%= form.text_field :pedido_id %>
  </div>

  <div class="field">
    <%= form.label :produto_id %>
    <%= form.select :produto_id, Produto.all.collect{|p| [p.nome, p.id]}, {}%>
  </div>

  <div class="field">
    <%= form.label :valor %>
    <%= form.text_field :valor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedido_produtos/edit.html.erb
<h1>Editing Pedido Produto</h1>

<%= render 'form', pedido_produto: @pedido_produto %>

<%= link_to 'Show', @pedido_produto %> |
<%= link_to 'Back', pedido_produtos_path %>

app/views/pedido_produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedido Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Pedido</th>
      <th>Produto</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedido_produtos.each do |pedido_produto| %>
      <tr>
        <td><%= pedido_produto.pedido.id %></td>
        <td><%= pedido_produto.produto.nome %></td>
        <td><%= pedido_produto.valor %></td>
        <td><%= link_to 'Show', pedido_produto %></td>
        <td><%= link_to 'Edit', edit_pedido_produto_path(pedido_produto) %></td>
        <td><%= link_to 'Destroy', pedido_produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido Produto', new_pedido_produto_path %>

app/views/pedido_produtos/new.html.erb
<h1>New Pedido Produto</h1>

<%= render 'form', pedido_produto: @pedido_produto %>

<%= link_to 'Back', pedido_produtos_path %>

app/views/pedido_produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pedido:</strong>
  <%= @pedido_produto.pedido.id %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @pedido_produto.produto.nome %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @pedido_produto.valor %>
</p>

<%= link_to 'Edit', edit_pedido_produto_path(@pedido_produto) %> |
<%= link_to 'Back', pedido_produtos_path %>